### ISSUE TITLE
Non-alpha characters and truncation limits in names and previous names

### ISSUE THREAD

**Issue by JoyLindsay** [ut-effectiveness/usheUtils#1]
ushe student file submission errors in the following elements:

**S_06 Name:**
S_LAST cannot have non-alpha characters or spaces. Truncation limit = 60
S_FIRST cannot have non-alpha characters or spaces. Truncation limit = 15
S_MIDDLE cannot have non-alpha characters or spaces. Truncation limit = 15
S_SUFFIX cannot have non-alpha characters or spaces. Truncation limit = 4

**S_07 Student Previous Name:**
S_PREV_LAST cannot have non-alpha characters or spaces. Truncation limit = 60
S_PREV_FIRST cannot have non-alpha characters or spaces. Truncation limit = 15
S_PREV_MIDDLE cannot have non-alpha characters or spaces. Truncation limit = 15
S_PREV_SUFFIX cannot have non-alpha characters or spaces. Truncation limit = 4

**Comment by CraigDemke** [comment]
I think I fixed this just need to check it with @JoyBaule
