### ISSUE TITLE
Update C44 to map the new code SGP

### ISSUE THREAD

**Issue by andreabringhurst** [ut-effectiveness/usheUtils#10]
https://github.com/ut-effectiveness/usheUtils/blob/ad2d12652346dd5fb73d1acc9cf45528195c3a51/R/courses.R#L1467C1-L1484C1

A new schedule code (section_format_type) has been added for Fall 2024 (SGP) and needs to be incorporated into USHE utils. SGP should be coded to INV.

Update to:
section_format_type_code %in% c("MUN", "MUM", "ACT", "ENS", "SGP")	~	"INV",

**Comment by JoyLindsay** [comment]
Running the raw data file for Fall 2024 shows that there are currently six courses that will be impacted.

I double checked courses for Summer 2024, none are impacted ahead of Summer EOT file submission.

 @cdemkegit can this be updated in usheUtils this week?

**Comment by CraigDemke** [comment]
@JoyBaule I can update these this week for sure.

**Comment by JoyLindsay** [comment]
Closed with pull request #14, this updates element c_44 Instructional Type in the Courses file submission, includes SGP instruction type in the section_format_type_code ~ INV grouping.
