### ISSUE TITLE
Student type HS cannot have a PELL status

### ISSUE THREAD

**Issue by JoyLindsay** [ut-effectiveness/usheUtils#2]
Student type of HS cannot have a Pell status.

If S_17 = HS, S_44 must be NA.

If S_17 = HS and S_44 = E, then S_44 must be NA.

We have HS students who have filled out a FAFSA and are marked as E/eligible for Pell. However, they cannot submit a FAFSA now without a valid GED or HS diploma. The records that are still marked as eligible in Banner now must be cleared to show NA to be in federal compliance: https://studentaid.gov/understand-aid/eligibility/requirements

**Comment by CraigDemke** [comment]
I think I fixed this just need to check it with @JoyBaule
