### ISSUE TITLE
Courses File - Spacing in course days offered

### ISSUE THREAD

**Issue by JoyLindsay** [ut-effectiveness/usheUtils#3]
**C_17/C_DAYS**

Remove spaces between course days of the week.

Character limit: 7, cannot have spaces between the days of the week.

**C_25/C_DAYS2**

Remove spaces between course days of the week.

Character limit: 7, cannot have spaces between the days of the week.

**C_33/C_DAYS 3**

Remove spaces between course days of the week.

Character limit: 7, cannot have spaces between the days of the week.

**Comment by CraigDemke** [comment]
I think I fixed this just need to test it with @JoyBaule
