### ISSUE TITLE
ushe_graduation_file_submission: g_10 degree type

### ISSUE THREAD

**Issue by JoyLindsay** [ut-effectiveness/usheUtils#5]
The degree type for certificates has changed for the 2024-25 compliance reporting cycle. 

All degrees marked CER0, CER1, and CERT need to be mutated to ACER to denote that certificates awarded by Utah Tech (a degree granting institution) are academic certificates and not technical certificates (as granted by technical colleges Salt Lake Community College, etc.)

All degrees marked MACC should be mutated to MAC per USHE data glossary guidelines.

It doesn't look like we have a function for g_10, it just pulls in the degree_id.

**Comment by JoyLindsay** [comment]
@cdemkegit I had an additional change to g_10 while submitting the file this week. In addition to wanting all certificates to be reported as ACER, they also want our masters  of MACC to report as MAC. I did a mutate statement in the submission file for this series.

**Comment by CraigDemke** [comment]
pull request on  #14  will resolve this issue.
