### ISSUE TITLE
ushe_graduation_submission_file g_12: cumulative transfer credit hours accepted

### ISSUE THREAD

**Issue by JoyLindsay** [ut-effectiveness/usheUtils#7]
It looks like there is an error in how element g_12 is being computed. The data is coming into the raw data file correctly, but when we generate the submission file, element g_12 is converting the total transfer credit hours to a negative number. 

https://github.com/ut-effectiveness/usheUtils/blob/ad2d12652346dd5fb73d1acc9cf45528195c3a51/R/graduation.R#L202C1-L220C1

g_12 <- function(input_df=usheUtils::fake_graduation_df) {

  output_df <- input_df %>%
    # Calculate intermediate fields
    mutate( g_trans_total_itermediate = (as.numeric(transfer_cumulative_credits_earned) -
                                         as.numeric(total_cumulative_credits_attempted_other_sources)) ) %>%
    mutate( g_trans_total = round(g_trans_total_itermediate, digits = 1) )  %>%
    # Append USHE data element g_12
    mutate(g_12 = g_trans_total)

  return(output_df)
}

**Comment by JoyLindsay** [comment]
@cdemkegit I had a couple of this type of error show up on the graduation snapshot fix file. The student's had their cumulative transfer hours pulling into the submission file as a negative number. They are correct in the raw data, it is creating an error in computation. I can provide you with id numbers for testing if you need an example.

**Comment by CraigDemke** [comment]
@JoyBaule I made a new branch dev_branch2 (because I played around with pkgdown and changed too many files in the dev_branch) could run the dev_branch2 and see if the changes I made fixed the issue?

**Comment by JoyLindsay** [comment]
Closed with pull request #14, this fixes the bug in elements g_12 cumulative transfer credit hours accepted in the Graduation file submission that was creating a negative credit hours accepted error.
