### ISSUE TITLE
Determine the impact of Courses changing from INV to OTH

### ISSUE THREAD

**Issue by andreabringhurst** [ut-effectiveness/usheUtils#9]
https://github.com/ut-effectiveness/usheUtils/blob/ad2d12652346dd5fb73d1acc9cf45528195c3a51/R/courses.R#L1467C1-L1483C2

@JoyBaule Determine the impact of courses changing codes from INV to OTH.
This is in reference to the Email from Vicki last week that showed the errors when the Spring 2024 courses were rolled to Spring 2025.

We know it is an issue for Spring. It may also be an issue for Fall 2024 3rd Week Report.

**Comment by JoyLindsay** [comment]
@andreabr-dixie At present there are 24 courses for Fall 2024 where the section_format_type_code is OTH. These are primarily athletics (FAST) but there is a Fusion Ensemble course (MUSC) and two theater workshop courses (THEA). There are also two Individualized Studies Labs (INDS), several Computer Literacy courses (CIS) and a Spec Function Officer Training course (CJ).
